#!/bin/sh
#
# git prepare-commit-msg hook for automatically prepending an issue key
# from the start of the current branch name to commit messages.

# check if commit is merge commit
if [ $2 -eq merge ]; then
    exit
fi

ISSUE_KEY=`git rev-parse --abbrev-ref HEAD | sed -e 's/.*\(DEV-[0-9]*\).*/\1/'`
BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`

if [ $? -ne 0 ]; then
    # no issue key in branch, use the default message
    exit
fi
# issue key matched from branch prefix, prepend to commit message

if [ $ISSUE_KEY = $BRANCH_NAME ]; then
	# nothing to do
	exit
else
	originalmessage=`cat $1`
	echo "$ISSUE_KEY - $originalmessage" > $1
fi